import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('hedge', {
  loadData: () => ipcRenderer.invoke('data:load'),
  saveData: (data: unknown) => ipcRenderer.invoke('data:save', data),
  configureInventory: (input: unknown) => ipcRenderer.invoke('inventory:configure', input),
  readGitInventory: () => ipcRenderer.invoke('inventory:git-read'),
  writeGitInventory: (source: string) => ipcRenderer.invoke('inventory:git-write', source),
  resetLocalData: () => ipcRenderer.invoke('app:reset-local-data'),
  getUpdateStatus: () => ipcRenderer.invoke('update:status'),
  getUpdateSettings: () => ipcRenderer.invoke('update:settings'),
  setUpdateSettings: (input: unknown) => ipcRenderer.invoke('update:settings', input),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  openLatestRelease: () => ipcRenderer.invoke('update:open-release'),
  onUpdateStatus: (callback: (status: unknown) => void) => { const listener = (_: unknown, status: unknown) => callback(status); ipcRenderer.on('update:status', listener); return () => ipcRenderer.removeListener('update:status', listener); },
  readClipboardText: () => ipcRenderer.invoke('clipboard:read-text'),
  writeClipboardText: (value: string) => ipcRenderer.invoke('clipboard:write-text', value),
  getRepository: () => ipcRenderer.invoke('repo:get'),
  getRepositoryStatus: () => ipcRenderer.invoke('repo:status'),
  getRepositoryFreshness: () => ipcRenderer.invoke('repo:freshness'),
  openLocalRepository: (input: unknown) => ipcRenderer.invoke('repo:open-local', input),
  cloneRepository: (input: unknown) => ipcRenderer.invoke('repo:clone', input),
  updateRepository: (input: unknown) => ipcRenderer.invoke('repo:update', input),
  testRepositoryConnection: () => ipcRenderer.invoke('repo:test-connection'),
  commitRepository: (message: string) => ipcRenderer.invoke('repo:commit', message),
  pullRepository: () => ipcRenderer.invoke('repo:pull'),
  pushRepository: () => ipcRenderer.invoke('repo:push'),
  resolveRepositoryConflicts: (input: unknown) => ipcRenderer.invoke('repo:resolve-conflicts', input),
  listWikiPages: () => ipcRenderer.invoke('wiki:list'),
  listWikiFolders: () => ipcRenderer.invoke('wiki:list-folders'),
  readWikiPage: (path: string) => ipcRenderer.invoke('wiki:read', path),
  writeWikiPage: (path: string, contents: string) => ipcRenderer.invoke('wiki:write', path, contents),
  createWikiPage: (section: string, name: string, parentPath?: string) => ipcRenderer.invoke('wiki:create', section, name, parentPath),
  createWikiFolder: (section: string, name: string, parentPath?: string) => ipcRenderer.invoke('wiki:create-folder', section, name, parentPath),
  moveWikiPage: (sourcePath: string, targetFolder: string) => ipcRenderer.invoke('wiki:move-page', sourcePath, targetFolder),
  ensureSessionWikiPage: (sessionId: string, sessionName: string, host: string) => ipcRenderer.invoke('wiki:session-page', sessionId, sessionName, host),
  choosePrivateKey: () => ipcRenderer.invoke('key:choose'),
  listSshKeys: () => ipcRenderer.invoke('keys:list'),
  generateSshKey: (input: unknown) => ipcRenderer.invoke('keys:generate', input),
  importSshKey: () => ipcRenderer.invoke('keys:import'),
  copyPublicKey: (privateKeyPath: string) => ipcRenderer.invoke('keys:copy-public', privateKeyPath),
  deleteSshKey: (privateKeyPath: string) => ipcRenderer.invoke('keys:delete', privateKeyPath),
  installPublicKey: (connectionId: string, privateKeyPath: string) => ipcRenderer.invoke('keys:install', connectionId, privateKeyPath),
  removePublicKey: (connectionId: string, privateKeyPath: string) => ipcRenderer.invoke('keys:remove', connectionId, privateKeyPath),
  getInstalledPublicKeys: (connectionId: string) => ipcRenderer.invoke('keys:remote-list', connectionId),
  connect: (request: unknown) => ipcRenderer.invoke('ssh:connect', request),
  write: (id: string, data: string) => ipcRenderer.send('ssh:write', id, data),
  resize: (id: string, cols: number, rows: number) => ipcRenderer.send('ssh:resize', id, cols, rows),
  disconnect: (id: string) => ipcRenderer.send('ssh:disconnect', id),
  trustHost: (id: string, accept: boolean) => ipcRenderer.send('ssh:trust', id, accept),
  clearKnownHost: (host: string, port: number) => ipcRenderer.invoke('host-key:clear', host, port),
  clearAllKnownHosts: () => ipcRenderer.invoke('host-key:clear-all'),
  getSecureStorageStatus: () => ipcRenderer.invoke('security:storage-status'),
  listCredentialSets: () => ipcRenderer.invoke('credentials:list'),
  saveCredentialSet: (input: unknown) => ipcRenderer.invoke('credentials:save', input),
  deleteCredentialSet: (id: string) => ipcRenderer.invoke('credentials:delete', id),
  onSshEvent: (callback: (event: unknown) => void) => {
    const listener = (_: unknown, event: unknown) => callback(event);
    ipcRenderer.on('ssh:event', listener); return () => ipcRenderer.removeListener('ssh:event', listener);
  },
  onHostKey: (callback: (event: unknown) => void) => {
    const listener = (_: unknown, event: unknown) => callback(event);
    ipcRenderer.on('ssh:host-key', listener); return () => ipcRenderer.removeListener('ssh:host-key', listener);
  },
  startPing: (host: string, monitorId: string) => ipcRenderer.invoke('ping:start', host, monitorId),
  startTcpMonitor: (host: string, port: number, monitorId: string) => ipcRenderer.invoke('tcp-monitor:start', host, port, monitorId),
  stopPing: (id: string) => ipcRenderer.send('ping:stop', id),
  onPingSample: (callback: (sample: unknown) => void) => {
    const listener = (_: unknown, sample: unknown) => callback(sample);
    ipcRenderer.on('ping:sample', listener); return () => ipcRenderer.removeListener('ping:sample', listener);
  },
  createBrowser: (tabId: string, url: string, bounds: unknown, darkMode: boolean) => ipcRenderer.invoke('browser:create', tabId, url, bounds, darkMode),
  openRemoteDesktop: (protocol: 'rdp' | 'vnc', host: string, port: number, username?: string, preferredClient?: string) => ipcRenderer.invoke('remote-desktop:open', protocol, host, port, username, preferredClient),
  createVncBridge: (tabId: string, host: string, port: number) => ipcRenderer.invoke('vnc:create', tabId, host, port),
  destroyVncBridge: (tabId: string) => ipcRenderer.send('vnc:destroy', tabId),
  setBrowserDarkMode: (tabId: string, enabled: boolean) => ipcRenderer.invoke('browser:dark-mode', tabId, enabled),
  setBrowserBounds: (tabId: string, bounds: unknown) => ipcRenderer.send('browser:bounds', tabId, bounds),
  setBrowserVisible: (tabId: string, visible: boolean) => ipcRenderer.send('browser:visible', tabId, visible),
  destroyBrowser: (tabId: string) => ipcRenderer.send('browser:destroy', tabId),
  navigateBrowser: (tabId: string, action: string, value?: string) => ipcRenderer.invoke('browser:navigate', tabId, action, value),
  openBrowserExternal: (tabId: string, url?: string) => ipcRenderer.invoke('browser:external', tabId, url),
  onBrowserEvent: (callback: (event: unknown) => void) => { const listener = (_: unknown, event: unknown) => callback(event); ipcRenderer.on('browser:event', listener); return () => ipcRenderer.removeListener('browser:event', listener); },
  onBrowserCertificate: (callback: (event: unknown) => void) => { const listener = (_: unknown, event: unknown) => callback(event); ipcRenderer.on('browser:certificate', listener); return () => ipcRenderer.removeListener('browser:certificate', listener); },
  respondBrowserCertificate: (tabId: string, accepted: boolean) => ipcRenderer.send('browser:certificate-response', tabId, accepted),
  listRemoteFiles: (id: string, path: string) => ipcRenderer.invoke('sftp:list', id, path),
  uploadRemoteFile: (id: string, remoteDirectory: string) => ipcRenderer.invoke('sftp:upload', id, remoteDirectory),
  downloadRemoteFile: (id: string, remotePath: string) => ipcRenderer.invoke('sftp:download', id, remotePath),
  uploadScpFile: (id: string, remoteDirectory: string) => ipcRenderer.invoke('scp:upload', id, remoteDirectory),
  downloadScpFile: (id: string, remotePath: string) => ipcRenderer.invoke('scp:download', id, remotePath)
});
