import { useState } from 'react';
import type { AppData, CredentialSet, RepositoryInput } from './types';
import { inventoryToYaml, yamlToInventory } from './InventoryEditor';

export default function FirstRunSetup({ data, credentials, onComplete }: { data: AppData; credentials: CredentialSet[]; onComplete: (data: AppData) => void }) {
  const [choice, setChoice] = useState<'choose' | 'git'>('choose'); const [mode, setMode] = useState<'local-repo' | 'remote'>('local-repo'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState<RepositoryInput>({ authorName: '', authorEmail: '', remoteUrl: '', branch: 'main', username: '', token: '' });
  const local = async () => { const inventorySettings = await window.hedge.configureInventory({ configured: true, mode: 'local' }); onComplete({ ...data, inventorySettings }); };
  const connectGit = async () => { setBusy(true); setError(''); try { let repository = await window.hedge.getRepository(); if (!repository) repository = mode === 'remote' ? await window.hedge.cloneRepository(form) : await window.hedge.openLocalRepository(form); if (!repository) return; const inventorySettings = await window.hedge.configureInventory({ configured: true, mode: 'git', repositoryPath: 'inventory.yml' }); const existing = await window.hedge.readGitInventory(); let next = data; if (existing) next = yamlToInventory(existing, data, credentials).data; else await window.hedge.writeGitInventory(inventoryToYaml(data, credentials)); await window.hedge.saveData(next); onComplete({ ...next, inventorySettings }); } catch (failure) { setError(failure instanceof Error ? failure.message : String(failure)); } finally { setBusy(false); } };
  return <div className="first-run"><section><div className="first-run-brand"><img src="./hedgecon-logo.png" alt="" /><div><small>WELCOME TO HEDGECON</small><h1>Choose your inventory workspace</h1><p>Secrets always remain on this computer.</p></div></div>{choice === 'choose' ? <div className="workspace-choices"><button onClick={() => void local()}><strong>Local workspace</strong><span>Keep folders and sessions on this computer. Git can be connected later.</span></button><button onClick={() => setChoice('git')}><strong>Git-managed workspace</strong><span>Use an Ansible-compatible YAML inventory in a local or shared repository.</span></button></div> : <div className="first-run-form"><div className="mode-tabs"><button className={mode === 'local-repo' ? 'active' : ''} onClick={() => setMode('local-repo')}>Local Git repository</button><button className={mode === 'remote' ? 'active' : ''} onClick={() => setMode('remote')}>Shared Git server</button></div><div className="split"><label>Git author name<input required value={form.authorName} onChange={event => setForm({ ...form, authorName: event.target.value })} placeholder="Network Engineer" /></label><label>Git author email<input required type="email" value={form.authorEmail} onChange={event => setForm({ ...form, authorEmail: event.target.value })} placeholder="engineer@example.com" /></label></div>{mode === 'remote' && <><label>HTTPS repository URL<input required value={form.remoteUrl} onChange={event => setForm({ ...form, remoteUrl: event.target.value })} placeholder="https://gitea.example.net/network/inventory.git" /></label><div className="split"><label>Username<input value={form.username} onChange={event => setForm({ ...form, username: event.target.value })} /></label><label>Access token<input type="password" value={form.token} onChange={event => setForm({ ...form, token: event.target.value })} /></label></div></>}<p className="hint">Existing inventory.yml content is validated before it becomes the local session tree. Passwords and key material are rejected by the inventory parser.</p>{error && <p className="wiki-error">{error}</p>}<div className="actions"><button className="secondary" onClick={() => setChoice('choose')}>Back</button><button className="primary" disabled={busy || !form.authorName || !form.authorEmail || (mode === 'remote' && !form.remoteUrl)} onClick={() => void connectGit()}>{busy ? 'Connecting...' : mode === 'remote' ? 'Clone and continue' : 'Choose folder and continue'}</button></div></div>}</section></div>;
}
