import type { AppData, BrowserCertificatePrompt, BrowserEvent, ConnectRequest, CredentialSet, CredentialSetInput, DeviceIdentity, GitConflict, HostKeyPrompt, InventorySettings, PingSample, RepositoryFreshness, RepositoryInput, RepositoryMeta, RepositoryPushResult, RepositoryStatus, SecureStorageStatus, SerialEvent, SerialPortInfo, SessionLogSettings, SftpEntry, SshEvent, SshKeyInfo, SshTunnel, UiSettings, UpdateRelease, UpdateSettings, UpdateStatus, WikiFolder, WikiPage } from './types';

declare global {
  interface Window { hedge: {
    loadData(): Promise<AppData>;
    saveData(data: AppData): Promise<AppData>;
    configureInventory(input: InventorySettings): Promise<InventorySettings>;
    readGitInventory(): Promise<string | null>;
    writeGitInventory(source: string): Promise<boolean>;
    resetLocalData(): Promise<boolean>;
    getUpdateStatus(): Promise<UpdateStatus>;
    getUpdateSettings(): Promise<UpdateSettings>;
    setUpdateSettings(input: UpdateSettings): Promise<UpdateSettings>;
    checkForUpdates(): Promise<UpdateStatus>;
    listUpdateReleases(): Promise<UpdateRelease[]>;
    selectUpdateRelease(tag: string): Promise<UpdateStatus>;
    downloadUpdate(): Promise<UpdateStatus>;
    installUpdate(): Promise<boolean>;
    openLatestRelease(): Promise<void>;
    openRegexHelp(): Promise<void>;
    openFeedbackIssue(input: { type: 'bug' | 'feature'; title: string; description: string; steps?: string; expected?: string; actual?: string; alternatives?: string; context?: string }): Promise<boolean>;
    getSessionLogSettings(): Promise<SessionLogSettings>;
    setSessionLogSettings(input: SessionLogSettings): Promise<SessionLogSettings>;
    openSessionLogFolder(): Promise<string>;
    onUpdateStatus(callback: (status: UpdateStatus) => void): () => void;
    readClipboardText(): Promise<string>;
    writeClipboardText(value: string): Promise<boolean>;
    getRepository(): Promise<RepositoryMeta | null>;
    getRepositoryStatus(): Promise<RepositoryStatus>;
    getRepositoryFreshness(): Promise<RepositoryFreshness>;
    openLocalRepository(input: RepositoryInput): Promise<RepositoryMeta | null>;
    cloneRepository(input: RepositoryInput): Promise<RepositoryMeta | null>;
    updateRepository(input: RepositoryInput): Promise<RepositoryMeta>;
    testRepositoryConnection(): Promise<{ remoteUrl: string; branch: string; branchFound: boolean }>;
    commitRepository(message: string): Promise<{ oid: string | null; status: RepositoryStatus }>;
    pullRepository(): Promise<RepositoryStatus>;
    pushRepository(): Promise<RepositoryPushResult>;
    resolveRepositoryConflicts(input: { localOid: string; remoteOid: string; resolutions: Array<Pick<GitConflict, 'path'> & { contents: string }> }): Promise<RepositoryPushResult>;
    listWikiPages(): Promise<WikiPage[]>;
    listWikiFolders(): Promise<WikiFolder[]>;
    readWikiPage(path: string): Promise<string>;
    writeWikiPage(path: string, contents: string): Promise<boolean>;
    writeWikiImage(pagePath: string, name: string, bytes: Uint8Array): Promise<{ path: string; markdownPath: string }>;
    readWikiImage(pagePath: string, imagePath: string): Promise<string>;
    createWikiPage(section: 'general' | 'vendors' | 'private', name: string, parentPath?: string): Promise<WikiPage>;
    createWikiFolder(section: 'general' | 'vendors' | 'private', name: string, parentPath?: string): Promise<WikiFolder>;
    renameWikiFolder(folderPath: string, name: string): Promise<WikiFolder>;
    deleteWikiFolder(folderPath: string): Promise<{ parentPath: string; movedPages: Array<{ from: string; to: string }> }>;
    moveWikiPage(sourcePath: string, targetFolder: string): Promise<WikiPage>;
    ensureSessionWikiPage(sessionId: string, sessionName: string, host: string): Promise<WikiPage>;
    ensurePrivateSessionNote(sessionId: string, sessionName: string, host: string): Promise<WikiPage>;
    choosePrivateKey(): Promise<string | null>;
    listSshKeys(): Promise<SshKeyInfo[]>;
    generateSshKey(input: { name: string; comment: string; passphrase: string }): Promise<SshKeyInfo>;
    importSshKey(): Promise<SshKeyInfo | null>;
    copyPublicKey(privateKeyPath: string): Promise<boolean>;
    deleteSshKey(privateKeyPath: string): Promise<boolean>;
    installPublicKey(connectionId: string, privateKeyPath: string): Promise<boolean>;
    removePublicKey(connectionId: string, privateKeyPath: string): Promise<boolean>;
    getInstalledPublicKeys(connectionId: string): Promise<string[]>;
    connect(request: ConnectRequest): Promise<{ connectionId: string }>;
    identifyDevice(connectionId: string): Promise<DeviceIdentity>;
    listTunnels(connectionId: string): Promise<SshTunnel[]>;
    startTunnel(connectionId: string, input: { type: 'local' | 'socks'; localPort: number; targetHost?: string; targetPort?: number }): Promise<SshTunnel>;
    stopTunnel(tunnelId: string): Promise<boolean>;
    listSerialPorts(): Promise<SerialPortInfo[]>;
    connectSerial(request: { connectionId: string; path: string; baudRate: number; dataBits: 5 | 6 | 7 | 8; stopBits: 1 | 1.5 | 2; parity: 'none' | 'even' | 'odd' | 'mark' | 'space' }): Promise<{ connectionId: string }>;
    writeSerial(connectionId: string, data: string): void;
    disconnectSerial(connectionId: string): void;
    onSerialEvent(callback: (event: SerialEvent) => void): () => void;
    write(connectionId: string, data: string): void;
    resize(connectionId: string, cols: number, rows: number): void;
    disconnect(connectionId: string): void;
    trustHost(connectionId: string, accept: boolean): void;
    clearKnownHost(host: string, port: number): Promise<boolean>;
    clearAllKnownHosts(): Promise<number>;
    getSecureStorageStatus(): Promise<SecureStorageStatus>;
    listCredentialSets(): Promise<CredentialSet[]>;
    copyCredentialField(id: string, field: 'username' | 'password'): Promise<boolean>;
    getRemoteCredential(id: string): Promise<{ username: string; password: string }>;
    saveCredentialSet(input: CredentialSetInput): Promise<CredentialSet>;
    deleteCredentialSet(id: string): Promise<boolean>;
    onSshEvent(callback: (event: SshEvent) => void): () => void;
    onHostKey(callback: (prompt: HostKeyPrompt) => void): () => void;
    startPing(host: string, monitorId: string): Promise<{ monitorId: string }>;
    startTcpMonitor(host: string, port: number, monitorId: string): Promise<{ monitorId: string }>;
    stopPing(monitorId: string): void;
    onPingSample(callback: (sample: PingSample) => void): () => void;
    createBrowser(tabId: string, url: string, bounds: { x: number; y: number; width: number; height: number }, darkMode: boolean): Promise<boolean>;
    openRemoteDesktop(protocol: 'rdp' | 'vnc', host: string, port: number, username?: string, preferredClient?: 'auto' | 'remmina' | 'freerdp', display?: { resolution: UiSettings['remoteDesktopResolution']; fullscreen: boolean }): Promise<{ client: string; installed?: boolean }>;
    createVncBridge(tabId: string, host: string, port: number): Promise<{ url: string }>;
    destroyVncBridge(tabId: string): void;
    setBrowserDarkMode(tabId: string, enabled: boolean): Promise<boolean>;
    captureBrowser(tabId: string): Promise<string>;
    setBrowserBounds(tabId: string, bounds: { x: number; y: number; width: number; height: number }): void;
    setBrowserVisible(tabId: string, visible: boolean): void;
    destroyBrowser(tabId: string): void;
    navigateBrowser(tabId: string, action: 'back' | 'forward' | 'reload' | 'url', value?: string): Promise<boolean>;
    openBrowserExternal(tabId: string, url?: string): Promise<void>;
    onBrowserEvent(callback: (event: BrowserEvent) => void): () => void;
    onBrowserCertificate(callback: (event: BrowserCertificatePrompt) => void): () => void;
    respondBrowserCertificate(tabId: string, accepted: boolean): void;
    listRemoteFiles(connectionId: string, path: string): Promise<SftpEntry[]>;
    uploadRemoteFile(connectionId: string, remoteDirectory: string): Promise<{ canceled: boolean; remotePath?: string }>;
    downloadRemoteFile(connectionId: string, remotePath: string): Promise<{ canceled: boolean; localPath?: string }>;
    uploadScpFile(connectionId: string, remoteDirectory: string): Promise<{ canceled: boolean; remotePath?: string }>;
    downloadScpFile(connectionId: string, remotePath: string): Promise<{ canceled: boolean; localPath?: string }>;
  }}
}
export {};
