import { useEffect, useMemo, useRef, useState } from 'react';
import { basicSetup } from 'codemirror';
import { EditorState } from '@codemirror/state';
import { EditorView, keymap } from '@codemirror/view';
import { defaultKeymap, indentWithTab } from '@codemirror/commands';
import { yaml as yamlLanguage } from '@codemirror/lang-yaml';
import { oneDark } from '@codemirror/theme-one-dark';
import { parse, stringify } from 'yaml';
import type { AppData, AuthMethod, CredentialSet, Folder, Session } from './types';
import ConfirmDialog from './ConfirmDialog';

type Mapping = Record<string, unknown>;
type Preview = { data: AppData; warnings: string[]; folders: number; sessions: number };
const isMapping = (value: unknown): value is Mapping => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const text = (value: unknown, fallback = '') => typeof value === 'string' ? value : typeof value === 'number' ? String(value) : fallback;
const slug = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9_-]+/g, '_').replace(/^_+|_+$/g, '') || 'group';

function uniqueKey(base: string, used: Set<string>) { let candidate = slug(base); for (let suffix = 2; used.has(candidate); suffix += 1) candidate = `${slug(base)}_${suffix}`; used.add(candidate); return candidate; }

export function inventoryToYaml(data: AppData, credentials: CredentialSet[]) {
  const credentialNames = new Map(credentials.map(item => [item.id, item.name]));
  const folderChildren = (parentId: string | null): Mapping => { const output: Mapping = {}; const used = new Set<string>(); for (const folder of data.folders.filter(item => (item.parentId ?? null) === parentId)) output[uniqueKey(folder.name, used)] = groupFor(folder); return output; };
  const hostsFor = (folderId: string | null): Mapping => { const output: Mapping = {}; const used = new Set<string>(); for (const session of data.sessions.filter(item => (item.folderId ?? null) === folderId)) { const host: Mapping = { ansible_host: session.host, ansible_port: session.port, ansible_user: session.username, hedgecon_name: session.name, hedgecon_id: session.id, hedgecon_auth: session.authMethod }; if (session.privateKeyPath) host.ansible_ssh_private_key_file = session.privateKeyPath; const credentialName = session.credentialSetId ? credentialNames.get(session.credentialSetId) : undefined; if (credentialName) host.hedgecon_credential_set = credentialName; output[uniqueKey(session.name, used)] = host; } return output; };
  const groupFor = (folder: Folder): Mapping => { const group: Mapping = { vars: { hedgecon_name: folder.name, hedgecon_id: folder.id } }; const hosts = hostsFor(folder.id); const children = folderChildren(folder.id); if (Object.keys(hosts).length) group.hosts = hosts; if (Object.keys(children).length) group.children = children; return group; };
  const all: Mapping = {}; const unfiled = hostsFor(null); const children = folderChildren(null); if (Object.keys(unfiled).length) all.hosts = unfiled; if (Object.keys(children).length) all.children = children;
  return `# HedgeCon inventory — compatible with Ansible YAML inventory\n# Secrets are intentionally excluded.\n${stringify({ all }, { indent: 2, lineWidth: 0 })}`;
}

function rejectSecrets(value: unknown, path = 'all') {
  if (!isMapping(value)) return;
  for (const [key, child] of Object.entries(value)) { if (/^(?:ansible_(?:ssh_)?pass(?:word)?|ansible_become_pass(?:word)?|password|passphrase)$/i.test(key)) throw new Error(`Secret field “${path}.${key}” is not allowed. Use a HedgeCon credential set instead.`); if (isMapping(child)) rejectSecrets(child, `${path}.${key}`); }
}

export function yamlToInventory(source: string, current: AppData, credentials: CredentialSet[]): Preview {
  const parsed: unknown = parse(source); if (!isMapping(parsed) || !isMapping(parsed.all)) throw new Error('An Ansible YAML inventory must contain an “all” group.'); rejectSecrets(parsed);
  const folders: Folder[] = []; const sessions: Session[] = []; const warnings: string[] = []; const credentialIds = new Map(credentials.map(item => [item.name.toLowerCase(), item.id])); const existingFolders = new Map(current.folders.map(item => [item.id, item])); const existingSessions = new Map(current.sessions.map(item => [item.id, item])); const hostKeys = new Set<string>();
  const walkGroup = (groupName: string, rawGroup: unknown, parentId: string | null, inherited: Mapping, isRoot = false) => { const group = isMapping(rawGroup) ? rawGroup : {}; const vars = { ...inherited, ...(isMapping(group.vars) ? group.vars : {}) }; let folderId = parentId; if (!isRoot) { const requestedId = text(vars.hedgecon_id); const existing = requestedId ? existingFolders.get(requestedId) : undefined; folderId = existing?.id ?? (requestedId || crypto.randomUUID()); folders.push({ id: folderId, name: text(vars.hedgecon_name, groupName), parentId, createdAt: existing?.createdAt ?? new Date().toISOString() }); }
    if (isMapping(group.hosts)) for (const [alias, rawHost] of Object.entries(group.hosts)) { const hostVars = { ...vars, ...(isMapping(rawHost) ? rawHost : {}) }; const address = text(hostVars.ansible_host, alias); const port = Number(hostVars.ansible_port ?? 22); if (!address || !Number.isInteger(port) || port < 1 || port > 65535) { warnings.push(`Skipped ${alias}: invalid host or port.`); continue; } const dedupe = `${address.toLowerCase()}:${port}`; if (hostKeys.has(dedupe)) { warnings.push(`Skipped duplicate host ${alias} (${address}:${port}).`); continue; } hostKeys.add(dedupe); const requestedId = text(hostVars.hedgecon_id); const existing = requestedId ? existingSessions.get(requestedId) : undefined; const credentialName = text(hostVars.hedgecon_credential_set); const credentialSetId = credentialName ? credentialIds.get(credentialName.toLowerCase()) ?? null : null; if (credentialName && !credentialSetId) warnings.push(`${alias}: credential set “${credentialName}” was not found.`); const privateKeyPath = text(hostVars.ansible_ssh_private_key_file) || undefined; const authMethod: AuthMethod = text(hostVars.hedgecon_auth) === 'privateKey' || privateKeyPath ? 'privateKey' : 'password'; const now = new Date().toISOString(); sessions.push({ id: existing?.id ?? (requestedId || crypto.randomUUID()), name: text(hostVars.hedgecon_name, alias), host: address, port, username: text(hostVars.ansible_user), folderId, authMethod, privateKeyPath, credentialSetId, createdAt: existing?.createdAt ?? now, updatedAt: now }); }
    if (isMapping(group.children)) for (const [childName, child] of Object.entries(group.children)) walkGroup(childName, child, folderId, vars);
  };
  walkGroup('all', parsed.all, null, {}, true); return { data: { folders, sessions }, warnings, folders: folders.length, sessions: sessions.length };
}

export default function InventoryEditor({ data, credentials, onApply, onClose }: { data: AppData; credentials: CredentialSet[]; onApply: (data: AppData) => void; onClose: () => void }) {
  const initial = useMemo(() => inventoryToYaml(data, credentials), [data, credentials]); const mount = useRef<HTMLDivElement>(null); const view = useRef<EditorView | null>(null); const [source, setSource] = useState(initial); const [error, setError] = useState(''); const [preview, setPreview] = useState<Preview | null>(null); const [confirmApply, setConfirmApply] = useState(false);
  useEffect(() => { if (!mount.current) return; view.current = new EditorView({ parent: mount.current, state: EditorState.create({ doc: initial, extensions: [basicSetup, keymap.of([...defaultKeymap, indentWithTab]), yamlLanguage(), oneDark, EditorView.lineWrapping, EditorView.updateListener.of(update => { if (update.docChanged) { setSource(update.state.doc.toString()); setPreview(null); setError(''); } })] }) }); return () => view.current?.destroy(); }, []);
  const validate = () => { try { const result = yamlToInventory(source, data, credentials); setPreview(result); setError(''); } catch (failure) { setPreview(null); setError(failure instanceof Error ? failure.message : String(failure)); } };
  const loadGitInventory = async () => { try { const contents = await window.hedge.readGitInventory(); if (!contents) throw new Error('The repository does not contain inventory.yml yet.'); view.current?.dispatch({ changes: { from: 0, to: view.current.state.doc.length, insert: contents } }); setError(''); } catch (failure) { setError(failure instanceof Error ? failure.message : String(failure)); } };
  const publishGitInventory = async () => { try { yamlToInventory(source, data, credentials); await window.hedge.writeGitInventory(source); const result = await window.hedge.commitRepository('Update managed inventory'); if (result.status.repository.remoteUrl) await window.hedge.pushRepository(); setError(''); } catch (failure) { setError(failure instanceof Error ? failure.message : String(failure)); } };
  const importFile = async (file?: File) => { if (!file) return; const contents = await file.text(); view.current?.dispatch({ changes: { from: 0, to: view.current.state.doc.length, insert: contents } }); };
  return <div className="inventory-screen"><header><div><small>INVENTORY AS CODE</small><h2>YAML Inventory Editor</h2><p>{data.inventorySettings?.mode === 'git' ? 'Git-managed inventory.yml is the configured source of truth.' : 'Optional Ansible-compatible management for folders and SSH sessions.'}</p></div><div className="inventory-actions">{data.inventorySettings?.mode === 'git' && <><button className="secondary" onClick={() => void loadGitInventory()}>Load from Git</button><button className="primary" onClick={() => void publishGitInventory()}>Commit & push</button></>}<label className="secondary inventory-import">Open YAML<input type="file" accept=".yml,.yaml,application/yaml,text/yaml" onChange={event => void importFile(event.target.files?.[0])} /></label><button className="secondary" onClick={() => { const generated = inventoryToYaml(data, credentials); view.current?.dispatch({ changes: { from: 0, to: view.current.state.doc.length, insert: generated } }); }}>Reset from GUI</button><button className="secondary" onClick={onClose}>Close</button></div></header><div className="inventory-editor" ref={mount} /><footer><div>{error ? <span className="inventory-error">{error}</span> : preview ? <span className="inventory-valid">Valid inventory: {preview.folders} folders and {preview.sessions} sessions.{preview.warnings.length ? ` ${preview.warnings.length} warning(s).` : ''}</span> : <span>Edit or load an inventory, then validate and preview it before applying.</span>}</div><div><button className="secondary" onClick={validate}>Validate & preview</button><button className="primary" disabled={!preview} onClick={() => setConfirmApply(true)}>Apply inventory</button></div></footer>{preview?.warnings.length ? <aside className="inventory-warnings"><strong>Import warnings</strong>{preview.warnings.map((warning, index) => <div key={index}>{warning}</div>)}</aside> : null}{confirmApply && preview && <ConfirmDialog eyebrow="INVENTORY CHANGE" title="Replace the current inventory?" message={`This will replace ${data.folders.length} folders and ${data.sessions.length} sessions with ${preview.folders} folders and ${preview.sessions} sessions. Credential secrets are not changed.`} confirmLabel="Apply inventory" danger onCancel={() => setConfirmApply(false)} onConfirm={() => { onApply({ ...preview.data, inventorySettings: data.inventorySettings }); setConfirmApply(false); onClose(); }} />}</div>;
}
