import { FormEvent, useMemo, useState } from 'react';
import type { CommandMacro, Folder, SessionPlatform } from './types';

const platforms: Array<{ id: SessionPlatform; label: string }> = [
  { id: 'linux', label: 'Linux' },
  { id: 'windows', label: 'Windows' },
  { id: 'network', label: 'Network device' },
  { id: 'unspecified', label: 'Unspecified' },
];
const blank = (): CommandMacro => ({ id: crypto.randomUUID(), name: '', description: '', command: '', runImmediately: false, folderIds: [], platforms: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });

export default function MacroLibrary({ macros, folders, onChange, onClose }: { macros: CommandMacro[]; folders: Folder[]; onChange: (macros: CommandMacro[]) => void; onClose: () => void }) {
  const [query, setQuery] = useState('');
  const [editing, setEditing] = useState<CommandMacro | null>(null);
  const [deleting, setDeleting] = useState<CommandMacro | null>(null);
  const filtered = useMemo(() => macros.filter(macro => `${macro.name} ${macro.description || ''} ${macro.command}`.toLowerCase().includes(query.trim().toLowerCase())), [macros, query]);
  const save = (macro: CommandMacro) => { onChange([...macros.filter(item => item.id !== macro.id), { ...macro, updatedAt: new Date().toISOString() }]); setEditing(null); };
  return <div className="macro-screen"><header><div><small>COMMAND LIBRARY</small><h2>Macros</h2><p>Reusable commands with session-aware favourites and prompted variables.</p></div><div><button className="primary" onClick={() => setEditing(blank())}>＋ New macro</button><button className="secondary" onClick={onClose}>Close</button></div></header><aside className="macro-nav"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search commands..." /><div className="macro-nav-heading">ALL MACROS <span>{filtered.length}</span></div>{filtered.map(macro => <button key={macro.id} onClick={() => setEditing({ ...macro, folderIds: [...macro.folderIds], platforms: [...macro.platforms] })}><strong>{macro.name}</strong><small>{macro.description || macro.command}</small></button>)}</aside><main className="macro-board"><div className="macro-board-heading"><div><small>BUTTON BOARD</small><h3>{query ? 'Search results' : 'All commands'}</h3></div></div><div className="macro-grid">{filtered.map(macro => <article key={macro.id}><button className="macro-tile" onClick={() => setEditing({ ...macro, folderIds: [...macro.folderIds], platforms: [...macro.platforms] })}><span>›_</span><strong>{macro.name}</strong><small>{macro.description || 'Reusable command'}</small><code>{macro.command}</code></button><button className="macro-delete" onClick={() => setDeleting(macro)} title={`Delete ${macro.name}`}>×</button></article>)}{!filtered.length && <div className="macro-empty"><strong>No macros found</strong><span>Create a reusable command to start your button board.</span></div>}</div></main>{editing && <MacroDialog macro={editing} folders={folders} onCancel={() => setEditing(null)} onSave={save} />}{deleting && <div className="overlay"><section className="dialog folder-dialog"><div className="dialog-title"><div><small>DELETE MACRO</small><h2>Delete “{deleting.name}”?</h2></div><button className="icon-button" onClick={() => setDeleting(null)}>×</button></div><p className="hint">This removes the macro from every session’s command board.</p><div className="actions"><button className="secondary" onClick={() => setDeleting(null)}>Cancel</button><button className="danger-button" onClick={() => { onChange(macros.filter(item => item.id !== deleting.id)); setDeleting(null); }}>Delete macro</button></div></section></div>}</div>;
}

function MacroDialog({ macro, folders, onCancel, onSave }: { macro: CommandMacro; folders: Folder[]; onCancel: () => void; onSave: (macro: CommandMacro) => void }) {
  const [form, setForm] = useState(macro);
  const submit = (event: FormEvent) => { event.preventDefault(); if (form.name.trim() && form.command.trim()) onSave({ ...form, name: form.name.trim(), description: form.description?.trim(), command: form.command.trim() }); };
  const toggleFolder = (id: string) => setForm({ ...form, folderIds: form.folderIds.includes(id) ? form.folderIds.filter(value => value !== id) : [...form.folderIds, id] });
  const togglePlatform = (id: SessionPlatform) => setForm({ ...form, platforms: form.platforms.includes(id) ? form.platforms.filter(value => value !== id) : [...form.platforms, id] });
  return <div className="overlay"><form className="dialog macro-dialog" onSubmit={submit}><div className="dialog-title"><div><small>COMMAND MACRO</small><h2>{macro.name ? 'Edit macro' : 'New macro'}</h2></div><button type="button" className="icon-button" onClick={onCancel}>×</button></div><label>Name<input autoFocus required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Update Linux packages" /></label><label>Description <em>optional</em><input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Refresh and upgrade installed packages" /></label><label>Command template<textarea required value={form.command} onChange={event => setForm({ ...form, command: event.target.value })} placeholder={'show dot1x interface {{ interface }}'} /></label><p className="hint">Use <code>{'{{ variable }}'}</code> to prompt for a value.</p><label className="macro-run-toggle"><input type="checkbox" checked={Boolean(form.runImmediately)} onChange={event => setForm({ ...form, runImmediately: event.target.checked })} /><span><strong>Run immediately</strong><small>Send Enter after inserting the command. Leave off to review it at the prompt first.</small></span></label><div className="macro-targets"><section><strong>Favourite for folders</strong><small>No selection means it remains available through search.</small>{folders.map(folder => <label key={folder.id}><input type="checkbox" checked={form.folderIds.includes(folder.id)} onChange={() => toggleFolder(folder.id)} />{folder.name}</label>)}</section><section><strong>Favourite for platforms</strong><small>Matched against the platform saved on each session.</small>{platforms.map(platform => <label key={platform.id}><input type="checkbox" checked={form.platforms.includes(platform.id)} onChange={() => togglePlatform(platform.id)} />{platform.label}</label>)}</section></div><div className="actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary">Save macro</button></div></form></div>;
}
