import { FormEvent, useCallback, useEffect, useState } from 'react';
import type { SftpEntry } from './types';

const formatSize = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : bytes < 1073741824 ? `${(bytes / 1048576).toFixed(1)} MB` : `${(bytes / 1073741824).toFixed(1)} GB`;
const parentPath = (remotePath: string) => { if (remotePath === '.' || remotePath === '/') return remotePath; const clean = remotePath.replace(/\/+$/, ''); const index = clean.lastIndexOf('/'); return index < 0 ? '.' : index === 0 ? '/' : clean.slice(0, index); };

export default function RemoteFiles({ connectionId, host, onClose }: { connectionId: string; host: string; onClose: () => void }) {
  const [mode, setMode] = useState<'sftp' | 'scp'>('sftp'); const [remotePath, setRemotePath] = useState('.'); const [pathInput, setPathInput] = useState('.'); const [entries, setEntries] = useState<SftpEntry[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async (target = remotePath) => { if (!connectionId) return; setLoading(true); setMessage(''); try { const files = await window.hedge.listRemoteFiles(connectionId, target); setEntries(files.sort((a, b) => a.type === b.type ? a.name.localeCompare(b.name) : a.type === 'directory' ? -1 : 1)); setRemotePath(target); setPathInput(target); } catch (error) { setMessage(`${error instanceof Error ? error.message : String(error)} Try SCP if this host does not provide SFTP.`); } finally { setLoading(false); } }, [connectionId, remotePath]);
  useEffect(() => { if (mode === 'sftp') void load('.'); }, [connectionId, mode]);
  useEffect(() => { const panels = Array.from(document.querySelectorAll<HTMLElement>('.remote-files')); const panel = panels.find(candidate => candidate.querySelector('header strong')?.textContent === host && !candidate.querySelector('.remote-files-divider')); if (!panel) return; const divider = document.createElement('div'); divider.className = 'remote-files-divider'; divider.title = 'Drag to resize the file browser'; divider.addEventListener('pointerdown', event => { event.preventDefault(); const startX = event.clientX; const startWidth = panel.getBoundingClientRect().width; const areaWidth = panel.parentElement?.getBoundingClientRect().width ?? window.innerWidth; const move = (pointer: PointerEvent) => { const width = Math.max(280, Math.min(areaWidth - 180, startWidth + startX - pointer.clientX)); panel.style.width = `${width}px`; panel.style.flexBasis = `${width}px`; }; const finish = () => { document.body.classList.remove('resizing-files'); window.removeEventListener('pointermove', move); }; document.body.classList.add('resizing-files'); window.addEventListener('pointermove', move); window.addEventListener('pointerup', finish, { once: true }); }); panel.prepend(divider); return () => divider.remove(); }, [host]);
  const navigate = (event: FormEvent) => { event.preventDefault(); if (mode === 'sftp') void load(pathInput.trim() || '.'); };
  const sftpUpload = async () => { setLoading(true); setMessage(''); try { const result = await window.hedge.uploadRemoteFile(connectionId, remotePath); if (!result.canceled) { setMessage(`Uploaded ${result.remotePath}`); await load(remotePath); } } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setLoading(false); } };
  const sftpDownload = async (entry: SftpEntry) => { setLoading(true); setMessage(''); try { const result = await window.hedge.downloadRemoteFile(connectionId, entry.path); if (!result.canceled) setMessage(`Saved to ${result.localPath}`); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setLoading(false); } };
  const scpUpload = async () => { setLoading(true); setMessage(''); try { const result = await window.hedge.uploadScpFile(connectionId, pathInput.trim() || '.'); if (!result.canceled) setMessage(`Uploaded ${result.remotePath}`); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setLoading(false); } };
  const scpDownload = async () => { const target = pathInput.trim(); if (!target) return setMessage('Enter the full remote file path to download.'); setLoading(true); setMessage(''); try { const result = await window.hedge.downloadScpFile(connectionId, target); if (!result.canceled) setMessage(`Saved to ${result.localPath}`); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setLoading(false); } };
  return <aside className="remote-files"><header><div><small>FILE TRANSFER</small><strong>{host}</strong></div><div className="transfer-modes"><button className={mode === 'sftp' ? 'active' : ''} onClick={() => setMode('sftp')}>SFTP</button><button className={mode === 'scp' ? 'active' : ''} onClick={() => { setMode('scp'); setMessage(''); setPathInput(remotePath); }}>SCP</button></div><button onClick={onClose} title="Close file browser">×</button></header>{mode === 'sftp' ? <><div className="file-actions"><button onClick={() => void load(parentPath(remotePath))} disabled={loading || remotePath === '.' || remotePath === '/'} title="Parent directory">↑</button><form onSubmit={navigate}><input value={pathInput} onChange={event => setPathInput(event.target.value)} aria-label="Remote path" /></form><button onClick={() => void load(remotePath)} disabled={loading} title="Refresh">↻</button><button className="upload-button" onClick={() => void sftpUpload()} disabled={loading}>Upload</button></div>{message && <div className="file-message">{message}</div>}<div className="file-list">{loading && !entries.length ? <div className="file-empty">Loading remote files…</div> : entries.map(entry => <div key={entry.path} className="file-entry" onDoubleClick={() => entry.type === 'directory' ? void load(entry.path) : void sftpDownload(entry)}><span className={`file-icon ${entry.type}`}>{entry.type === 'directory' ? '▰' : entry.type === 'link' ? '↗' : '·'}</span><div><strong>{entry.name}</strong><small>{entry.type === 'directory' ? 'Folder' : formatSize(entry.size)} · {new Date(entry.modifiedAt).toLocaleString()}</small></div>{entry.type !== 'directory' && <button onClick={() => void sftpDownload(entry)}>Download</button>}</div>)}{!loading && !entries.length && !message && <div className="file-empty">This directory is empty.</div>}</div><footer>Double-click folders to open and files to download.</footer></> : <div className="scp-panel"><p>SCP transfers use an explicit remote path because SCP cannot browse directories.</p><label>Remote directory or file path<input autoFocus value={pathInput} onChange={event => setPathInput(event.target.value)} placeholder="/var/tmp/firmware.bin" /></label><div className="scp-actions"><button onClick={() => void scpUpload()} disabled={loading}>Upload to directory</button><button onClick={() => void scpDownload()} disabled={loading}>Download file</button></div>{message && <div className="file-message">{message}</div>}<small>For upload, enter a directory. For download, enter the complete remote filename.</small></div>}</aside>;
}
