import { useEffect, useRef, useState } from 'react';
import { basicSetup } from 'codemirror';
import { EditorState } from '@codemirror/state';
import { EditorView, keymap } from '@codemirror/view';
import { defaultKeymap, indentWithTab } from '@codemirror/commands';
import { markdown } from '@codemirror/lang-markdown';
import { oneDark } from '@codemirror/theme-one-dark';
import type { Session } from './types';

export default function SessionNotesPanel({ session, onClose, onExpand }: { session: Session; onClose: () => void; onExpand: () => void }) {
  const mount = useRef<HTMLDivElement>(null); const panel = useRef<HTMLElement>(null); const editor = useRef<EditorView | null>(null); const currentSource = useRef('');
  const [panelWidth, setPanelWidth] = useState(420);
  const [pagePath, setPagePath] = useState(''); const [source, setSource] = useState(''); const [savedSource, setSavedSource] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [needsSetup, setNeedsSetup] = useState(false);
  useEffect(() => { let active = true; void window.hedge.getRepository().then(async repository => { if (!active) return; if (!repository) { setNeedsSetup(true); setLoading(false); return; } const page = await window.hedge.ensureSessionWikiPage(session.id, session.name, session.host); const contents = await window.hedge.readWikiPage(page.path); if (!active) return; setPagePath(page.path); setSource(contents); setSavedSource(contents); setLoading(false); }).catch(error => { if (active) { setMessage(error instanceof Error ? error.message : String(error)); setLoading(false); } }); return () => { active = false; }; }, [session.id]);
  useEffect(() => { currentSource.current = source; }, [source]);
  useEffect(() => { if (!mount.current || loading || needsSetup || !pagePath) return; editor.current = new EditorView({ parent: mount.current, state: EditorState.create({ doc: currentSource.current, extensions: [basicSetup, keymap.of([...defaultKeymap, indentWithTab]), markdown(), oneDark, EditorView.lineWrapping, EditorView.updateListener.of(update => { if (update.docChanged) setSource(update.state.doc.toString()); })] }) }); return () => { editor.current?.destroy(); editor.current = null; }; }, [loading, needsSetup, pagePath]);
  const save = async () => { if (!pagePath) return; setSaving(true); setMessage(''); try { await window.hedge.writeWikiPage(pagePath, source); setSavedSource(source); setMessage('Saved locally. Commit from the full Wiki when ready.'); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setSaving(false); } };
  const beginResize = (event: React.PointerEvent) => { event.preventDefault(); const container = panel.current?.parentElement; if (!panel.current || !container) return; const startX = event.clientX; const startWidth = panel.current.getBoundingClientRect().width; const maximum = Math.max(300, container.getBoundingClientRect().width - 240); const move = (pointer: PointerEvent) => setPanelWidth(Math.max(280, Math.min(maximum, startWidth - (pointer.clientX - startX)))); const finish = () => { window.removeEventListener('pointermove', move); document.body.classList.remove('resizing-notes'); }; document.body.classList.add('resizing-notes'); window.addEventListener('pointermove', move); window.addEventListener('pointerup', finish, { once: true }); };
  return <aside ref={panel} className="session-notes" style={{ flexBasis: panelWidth, width: panelWidth }}><div className="session-notes-divider" onPointerDown={beginResize} title="Drag to resize notes" /><header><div><small>SESSION NOTES</small><strong>{session.name}</strong></div><div><button onClick={onExpand} title="Open full Wiki">⛶</button><button onClick={onClose} title="Close notes">×</button></div></header>{loading ? <div className="session-notes-state">Loading notes...</div> : needsSetup ? <div className="session-notes-state"><strong>Wiki setup needed</strong><p>Create or connect a Git repository before saving session notes.</p><button className="primary" onClick={onExpand}>Set up Wiki</button></div> : <div className="session-notes-editor" ref={mount} />}<footer><span className={message && !message.startsWith('Saved') ? 'error' : ''}>{message || (source !== savedSource ? 'Unsaved changes' : 'Saved locally')}</span><button className="primary" disabled={saving || !pagePath || source === savedSource} onClick={() => void save()}>{saving ? 'Saving...' : 'Save'}</button></footer></aside>;
}
