import { FormEvent, useEffect, useState } from 'react';
import type { Session, SshTunnel } from './types';

export default function SshToolsPanel({ connectionId, session, onClose }: { connectionId: string; session: Session; onClose: () => void }) {
  const identity = session.detectedIdentity;
  const [tunnels, setTunnels] = useState<SshTunnel[]>([]); const [type, setType] = useState<'local' | 'socks'>('local'); const [localPort, setLocalPort] = useState(0); const [targetHost, setTargetHost] = useState(session.host); const [targetPort, setTargetPort] = useState(443); const [message, setMessage] = useState('');
  const refresh = () => window.hedge.listTunnels(connectionId).then(setTunnels).catch(() => setTunnels([]));
  useEffect(() => { void refresh(); const timer = window.setInterval(refresh, 2000); return () => window.clearInterval(timer); }, [connectionId]);
  const start = async (event: FormEvent) => { event.preventDefault(); setMessage(''); try { const tunnel = await window.hedge.startTunnel(connectionId, { type, localPort, ...(type === 'local' ? { targetHost, targetPort } : {}) }); setTunnels(current => [...current, tunnel]); setMessage(`${type === 'socks' ? 'SOCKS5 proxy' : 'Local tunnel'} listening on 127.0.0.1:${tunnel.localPort}.`); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  return <aside className="ssh-tools-panel"><header><div><small>SSH CONNECTION</small><h3>Device & tunnels</h3></div><button className="icon-button" onClick={onClose} aria-label="Close SSH tools">×</button></header>
    <section className="remembered-device"><small>REMEMBERED DEVICE</small><strong>{identity?.product || 'Unknown device'}</strong><span>{[identity?.hostname, identity?.vendor, identity?.version].filter(Boolean).join(' · ') || 'Information will be collected after connection.'}</span><em>{identity?.platform || 'unspecified'}</em></section>
    <section><div className="ssh-tools-heading"><div><strong>Active tunnels</strong><small>Available only on this computer.</small></div></div>{tunnels.map(tunnel => <div className="tunnel-row" key={tunnel.id}><div><strong>127.0.0.1:{tunnel.localPort}</strong><small>{tunnel.type === 'socks' ? 'SOCKS5 proxy' : `→ ${tunnel.targetHost}:${tunnel.targetPort}`} · {tunnel.connections} active</small></div><button className="danger-button" onClick={async () => { await window.hedge.stopTunnel(tunnel.id); void refresh(); }}>Stop</button></div>)}{!tunnels.length && <p className="hint">No tunnels are running through this SSH connection.</p>}</section>
    <form onSubmit={start}><div className="tunnel-type"><button type="button" className={type === 'local' ? 'active' : ''} onClick={() => setType('local')}>Local forward</button><button type="button" className={type === 'socks' ? 'active' : ''} onClick={() => setType('socks')}>SOCKS5 proxy</button></div><label>Local port<input type="number" min="0" max="65535" value={localPort} onChange={event => setLocalPort(Number(event.target.value))} /><small>Use 0 to select an available port automatically.</small></label>{type === 'local' && <div className="tunnel-target"><label>Destination host<input value={targetHost} onChange={event => setTargetHost(event.target.value)} /></label><label>Port<input type="number" min="1" max="65535" value={targetPort} onChange={event => setTargetPort(Number(event.target.value))} /></label></div>}<button className="primary" disabled={!connectionId}>Start tunnel</button></form>{message && <button className="ssh-tools-message" onClick={() => setMessage('')}>{message}</button>}
  </aside>;
}
