import { FormEvent, lazy, Suspense, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import type { CommandMacro, Folder, HostKeyPrompt, MacroFolder, Session, SshKeyInfo, UiSettings } from './types';
import PingMonitor from './PingMonitor';
import RemoteFiles from './RemoteFiles';
import ConfirmDialog from './ConfirmDialog';
import MacroBoard from './MacroBoard';
import { refreshTerminalPatternDecorations } from './terminalPatterns';

const SessionNotesPanel = lazy(() => import('./SessionNotesPanel'));

export default function TerminalView({ session, secret, active = true, macros = [], macroFolders = [], folders = [], onManageMacros = () => {}, onActivity = () => {}, onClose, onNotes = () => window.dispatchEvent(new CustomEvent('hedgecon:session-notes', { detail: session.id })) }: { session: Session; secret: string; active?: boolean; macros?: CommandMacro[]; macroFolders?: MacroFolder[]; folders?: Folder[]; onManageMacros?: () => void; onActivity?: () => void; onClose: () => void; onNotes?: () => void }) {
  const hostRef = useRef<HTMLDivElement>(null); const terminalRef = useRef<Terminal | null>(null);
  const onActivityRef = useRef(onActivity); useEffect(() => { onActivityRef.current = onActivity; }, [onActivity]);
  const [hostPrompt, setHostPrompt] = useState<HostKeyPrompt | null>(null);
  const [authFailed, setAuthFailed] = useState(false); const [retrySecret, setRetrySecret] = useState('');
  const [monitorOpen, setMonitorOpen] = useState(false);
  const [filesOpen, setFilesOpen] = useState(false); const [liveConnectionId, setLiveConnectionId] = useState('');
  const [notesOpen, setNotesOpen] = useState(false);
  const [macrosOpen, setMacrosOpen] = useState(false);
  const [keyPickerOpen, setKeyPickerOpen] = useState(false); const [availableKeys, setAvailableKeys] = useState<SshKeyInfo[]>([]); const [installedPublicKeys, setInstalledPublicKeys] = useState<string[]>([]); const [keyMessage, setKeyMessage] = useState(''); const [installingKey, setInstallingKey] = useState(''); const [keyToRemove, setKeyToRemove] = useState<SshKeyInfo | null>(null);
  const [attempt, setAttempt] = useState({ secret, overrideCredential: false, number: 0 });
  const readUiSettings = (): UiSettings => { const fallback: UiSettings = { theme: 'midnight', browserTheme: 'normal', linuxRdpClient: 'auto', remoteDesktopResolution: 'native', remoteDesktopFullscreen: false, terminalDefault: '#080c12', terminalForeground: '#d7e0ea', terminalMeanings: [], terminalPatterns: [] }; try { return { ...fallback, ...(JSON.parse(localStorage.getItem('hedgecon-ui-settings') || '') as Partial<UiSettings>) }; } catch { return fallback; } };
  const [uiSettings, setUiSettings] = useState(readUiSettings); const [terminalColour, setTerminalColour] = useState(() => readUiSettings().terminalDefault);
  const uiSettingsRef = useRef(uiSettings); useEffect(() => { uiSettingsRef.current = uiSettings; }, [uiSettings]);
  useEffect(() => { const update = (event: Event) => setUiSettings((event as CustomEvent<UiSettings>).detail); window.addEventListener('hedgecon:ui-settings', update); return () => window.removeEventListener('hedgecon:ui-settings', update); }, []);
  useEffect(() => { if (terminalRef.current) terminalRef.current.options.theme = { ...terminalRef.current.options.theme, background: terminalColour }; }, [terminalColour]);
  useEffect(() => { if (terminalRef.current) terminalRef.current.options.theme = { ...terminalRef.current.options.theme, foreground: uiSettings.terminalForeground }; }, [uiSettings.terminalForeground]);
  useEffect(() => { const stage = hostRef.current?.parentElement; const panel = stage?.closest('.terminal-panel'); const arrow = panel?.querySelector<HTMLButtonElement>('.terminal-bottom'); if (!stage || !arrow) return; stage.appendChild(arrow); return () => { const tools = panel?.querySelector('.terminal-tools'); if (tools?.isConnected && arrow.isConnected) tools.appendChild(arrow); }; }, []);
  useEffect(() => { const tools = hostRef.current?.closest('.terminal-panel')?.querySelector('.terminal-tools'); if (!tools) return; const button = document.createElement('button'); button.textContent = '›_ Macros'; button.title = 'Open command macros'; if (macrosOpen) button.className = 'active'; button.onclick = () => { setFilesOpen(false); setNotesOpen(false); setMacrosOpen(open => !open); }; tools.insertBefore(button, tools.querySelector('.terminal-bottom')); return () => button.remove(); }, [macrosOpen]);
  useEffect(() => { if (!macrosOpen) return; const host = document.createElement('div'); host.className = 'macro-panel-root'; const savedWidth = Math.max(220, Math.min(520, Number(localStorage.getItem('hedgecon-macro-panel-width')) || 300)); host.style.width = `${savedWidth}px`; host.style.flexBasis = `${savedWidth}px`; hostRef.current?.closest('.terminal-area')?.appendChild(host); const root = createRoot(host); root.render(<MacroBoard session={session} macros={macros} macroFolders={macroFolders} folders={folders} onPaste={(command, runImmediately) => { if (liveConnectionId) { terminalRef.current?.scrollToBottom(); window.hedge.write(liveConnectionId, `${command}${runImmediately ? '\r' : ''}`); } window.setTimeout(() => terminalRef.current?.focus(), 0); }} onClose={() => setMacrosOpen(false)} onManage={onManageMacros} />); return () => { window.setTimeout(() => { root.unmount(); host.remove(); }, 0); }; }, [macrosOpen, macros, macroFolders, folders, liveConnectionId, session, onManageMacros]);
  useEffect(() => { const stage = hostRef.current?.parentElement; if (!stage) return; const wrapper = document.createElement('div'); wrapper.className = 'terminal-colour-control'; const button = document.createElement('button'); button.className = 'terminal-colour-button'; button.type = 'button'; button.textContent = '◐'; const menu = document.createElement('div'); menu.className = 'terminal-colour-menu'; wrapper.onmouseenter = () => menu.style.removeProperty('display'); wrapper.onmouseleave = () => { menu.style.display = 'none'; button.blur(); }; const choices = [{ id: 'default', word: 'Default', colour: uiSettings.terminalDefault }, ...uiSettings.terminalMeanings]; let activeColour = terminalColour; const apply = (colour: string, word: string) => { activeColour = colour; setTerminalColour(colour); button.title = `Terminal colour: ${word}`; button.style.setProperty('--terminal-colour', colour); }; button.onclick = () => { const first = uiSettings.terminalMeanings[0]; if (!first) return; const turnOff = activeColour !== uiSettings.terminalDefault; apply(turnOff ? uiSettings.terminalDefault : first.colour, turnOff ? 'Default' : first.word); menu.style.display = 'none'; }; choices.forEach(choice => { const option = document.createElement('button'); option.type = 'button'; option.title = `Use ${choice.word}`; const swatch = document.createElement('i'); swatch.style.background = choice.colour; const label = document.createElement('span'); label.textContent = choice.word; option.append(swatch, label); option.onclick = event => { event.preventDefault(); event.stopPropagation(); apply(choice.colour, choice.word); menu.style.display = 'none'; button.blur(); }; menu.appendChild(option); }); const selected = choices.find(choice => choice.colour === terminalColour) ?? choices[0]; button.title = `Terminal colour: ${selected.word}`; button.style.setProperty('--terminal-colour', selected.colour); wrapper.append(button, menu); stage.appendChild(wrapper); return () => wrapper.remove(); }, [uiSettings]);
  const reconnectFailures = useRef(0); const suppressReconnect = useRef(false);
  const answerHostKey = (accepted: boolean) => { if (!hostPrompt) return; if (!accepted) suppressReconnect.current = true; window.hedge.trustHost(hostPrompt.connectionId, accepted); setHostPrompt(null); };
  const retryAuthentication = (event: FormEvent) => { event.preventDefault(); setAuthFailed(false); setAttempt(current => ({ secret: retrySecret, overrideCredential: Boolean(session.credentialSetId), number: current.number + 1 })); setRetrySecret(''); };

  useEffect(() => {
    const connectionId = crypto.randomUUID();
    setLiveConnectionId(connectionId);
    const terminal = new Terminal({ cursorBlink: true, scrollback: 10000, fontFamily: 'Cascadia Code, Consolas, monospace', fontSize: 14, theme: { background: terminalColour, foreground: uiSettings.terminalForeground, cursor: '#70d6b2', selectionBackground: '#264c48' } }); terminalRef.current = terminal;
    const fit = new FitAddon(); terminal.loadAddon(fit); terminal.open(hostRef.current!); fit.fit();
    let selectionTimer: number | undefined; const copySelection = () => { window.clearTimeout(selectionTimer); selectionTimer = window.setTimeout(() => { const selected = terminal.getSelection(); if (selected) void window.hedge.writeClipboardText(selected); }, 120); }; const selectionDisposable = terminal.onSelectionChange(copySelection);
    const pasteClipboard = (event: MouseEvent) => { event.preventDefault(); void window.hedge.readClipboardText().then(value => { if (value) { terminal.scrollToBottom(); window.hedge.write(connectionId, value); } }); }; hostRef.current!.addEventListener('contextmenu', pasteClipboard);
    terminal.writeln(`\x1b[38;2;112;214;178mConnecting to ${session.username}@${session.host}...\x1b[0m`);
    let authRejected = false; let reconnectScheduled = false; let reconnectTimer: number | undefined;
    const scheduleReconnect = () => { if (authRejected || suppressReconnect.current || reconnectScheduled) return; reconnectScheduled = true; const delay = Math.min(30000, 2000 * (2 ** reconnectFailures.current)); reconnectFailures.current += 1; terminal.writeln(`\r\n\x1b[38;2;240;190;100mConnection lost. Reconnecting in ${Math.round(delay / 1000)}s...\x1b[0m`); reconnectTimer = window.setTimeout(() => setAttempt(current => ({ ...current, number: current.number + 1 })), delay); };
    const removeEvents = window.hedge.onSshEvent((event) => {
      if (event.connectionId !== connectionId) return;
      onActivityRef.current();
      if (event.type === 'data') { const follow = terminal.buffer.active.viewportY >= terminal.buffer.active.baseY; terminal.write(event.data, () => { refreshTerminalPatternDecorations(terminal, uiSettingsRef.current.terminalPatterns, event.data); if (follow) terminal.scrollToBottom(); }); }
      else if (event.type === 'status') { reconnectFailures.current = 0; terminal.writeln(`\r\n\x1b[38;2;112;214;178m${event.data}\x1b[0m`); }
      else if (event.type === 'auth-error') { authRejected = true; terminal.writeln('\r\n\x1b[38;2;244;112;112mAuthentication rejected.\x1b[0m'); setAuthFailed(true); }
      else if (event.type === 'error') { terminal.writeln(`\r\n\x1b[38;2;244;112;112m${event.data}\x1b[0m`); scheduleReconnect(); }
      else { terminal.writeln(`\r\n\x1b[38;2;139;153;168m${event.data}\x1b[0m`); scheduleReconnect(); }
    });
    const removeHost = window.hedge.onHostKey((prompt: HostKeyPrompt) => { if (prompt.connectionId === connectionId) setHostPrompt(prompt); });
    terminal.onData(data => { terminal.scrollToBottom(); window.hedge.write(connectionId, data); });
    window.hedge.connect({ ...session, connectionId, ...(session.authMethod === 'password' ? { password: attempt.secret } : { passphrase: attempt.secret }), ...(attempt.overrideCredential ? { credentialOverride: attempt.secret } : {}) })
      .catch(error => terminal.writeln(`\r\n\x1b[38;2;244;112;112m${String(error)}\x1b[0m`));
    const resizeTerminal = () => { if (!hostRef.current?.clientWidth || !hostRef.current?.clientHeight) return; fit.fit(); terminal.scrollToBottom(); window.hedge.resize(connectionId, terminal.cols, terminal.rows); };
    let resizeFrame = 0; const scheduleResize = () => { window.cancelAnimationFrame(resizeFrame); resizeFrame = window.requestAnimationFrame(resizeTerminal); };
    const resize = new ResizeObserver(scheduleResize); resize.observe(hostRef.current!); window.addEventListener('resize', scheduleResize); scheduleResize();
    return () => { if (reconnectTimer !== undefined) window.clearTimeout(reconnectTimer); if (selectionTimer !== undefined) window.clearTimeout(selectionTimer); selectionDisposable.dispose(); hostRef.current?.removeEventListener('contextmenu', pasteClipboard); window.cancelAnimationFrame(resizeFrame); window.removeEventListener('resize', scheduleResize); resize.disconnect(); removeEvents(); removeHost(); window.hedge.disconnect(connectionId); terminal.dispose(); terminalRef.current = null; setLiveConnectionId(current => current === connectionId ? '' : current); };
  }, [session, attempt]);

  useEffect(() => {
    if (!active || macrosOpen) return;
    let focusFrame = 0;
    const settleFrame = window.requestAnimationFrame(() => {
      focusFrame = window.requestAnimationFrame(() => {
        if (!document.querySelector('.overlay')) terminalRef.current?.focus();
      });
    });
    return () => { window.cancelAnimationFrame(settleFrame); window.cancelAnimationFrame(focusFrame); };
  }, [active, macrosOpen]);

  return <section className="terminal-panel"><header><div><span className="status-dot" />{session.name}<small>{session.username}@{session.host}:{session.port}</small></div><button className="icon-button" onClick={onClose} aria-label="Close terminal">×</button></header><div className="terminal-area"><div className="terminal-stage"><div className="terminal" ref={hostRef} /></div>{filesOpen && <RemoteFiles connectionId={liveConnectionId} host={session.host} onClose={() => setFilesOpen(false)} />}{notesOpen && <Suspense fallback={<aside className="session-notes"><div className="session-notes-state">Loading notes...</div></aside>}><SessionNotesPanel session={session} onClose={() => setNotesOpen(false)} onExpand={onNotes} /></Suspense>}</div><div className="terminal-tools"><button onClick={() => setMonitorOpen(open => !open)} className={monitorOpen ? 'active' : ''} title={`${monitorOpen ? 'Close' : 'Open'} monitor for ${session.host}`}>⌁ Monitor</button><button onClick={() => { setNotesOpen(false); setFilesOpen(open => !open); }} className={filesOpen ? 'active' : ''} title="Browse remote files">▤ Files</button><button onClick={async () => { setKeyMessage('Reading keys from the host…'); setKeyPickerOpen(true); try { const [localKeys, remoteKeys] = await Promise.all([window.hedge.listSshKeys(), window.hedge.getInstalledPublicKeys(liveConnectionId)]); setAvailableKeys(localKeys.filter(key => key.publicKey)); setInstalledPublicKeys(remoteKeys); setKeyMessage(''); } catch (error) { setKeyMessage(`Could not read keys from ${session.host}: ${error instanceof Error ? error.message : String(error)}`); } }} title="Manage SSH public keys on this host">⌁ Keys</button><button onClick={() => { setFilesOpen(false); setNotesOpen(open => !open); }} className={notesOpen ? 'active' : ''} title={`Edit notes for ${session.name}`}>▧ Notes</button><button className="terminal-bottom" onClick={() => terminalRef.current?.scrollToBottom()} title="Jump to latest output" aria-label="Jump to latest output">↓</button></div>{monitorOpen && <PingMonitor host={session.host} port={session.port} onClose={() => setMonitorOpen(false)} />}
    {keyPickerOpen && <div className="overlay"><section className="dialog key-picker"><div className="dialog-title"><div><small>AUTHORIZED KEYS</small><h2>Manage public keys</h2></div><button className="icon-button" onClick={() => setKeyPickerOpen(false)}>×</button></div><p className="hint">Shows the actual state of <code>~/.ssh/authorized_keys</code> on {session.host}. This currently supports Linux, Unix, and network-device shells with standard POSIX commands.</p>{keyMessage && <p className={`key-install-message ${keyMessage.startsWith('Could not') ? 'error' : ''}`}>{keyMessage}</p>}<div className="key-picker-list">{availableKeys.length > 0 && <div className="key-section-label">INSTALLED ON THIS HOST</div>}{availableKeys.filter(key => Boolean(key.publicKey && installedPublicKeys.includes(key.publicKey))).map(key => <div className="key-picker-row" key={key.privateKeyPath}><div><strong>{key.name}<em>Installed</em></strong><small>{key.fingerprint}</small></div><div><button className="remove-remote" disabled={Boolean(installingKey)} onClick={() => setKeyToRemove(key)}>Remove</button></div></div>)}{availableKeys.length > 0 && !availableKeys.some(key => key.publicKey && installedPublicKeys.includes(key.publicKey)) && <p className="key-section-empty">None of your local keys are installed.</p>}{availableKeys.length > 0 && <div className="key-section-label">AVAILABLE TO INSTALL</div>}{availableKeys.filter(key => !key.publicKey || !installedPublicKeys.includes(key.publicKey)).map(key => <div className="key-picker-row" key={key.privateKeyPath}><div><strong>{key.name}</strong><small>{key.fingerprint}</small></div><div><button disabled={Boolean(installingKey)} onClick={async () => { setInstallingKey(key.privateKeyPath); setKeyMessage(`Installing ${key.name}…`); try { await window.hedge.installPublicKey(liveConnectionId, key.privateKeyPath); if (key.publicKey) setInstalledPublicKeys(current => [...current, key.publicKey!]); setKeyMessage(`${key.name} was installed successfully.`); } catch (error) { setKeyMessage(`Could not install ${key.name}: ${error instanceof Error ? error.message : String(error)}`); } finally { setInstallingKey(''); } }}>{installingKey === key.privateKeyPath ? 'Working…' : 'Install'}</button></div></div>)}{!availableKeys.length && <p>No keys with public-key files were found. Generate one in Settings first.</p>}</div><div className="actions"><button className="primary" disabled={Boolean(installingKey)} onClick={() => setKeyPickerOpen(false)}>Done</button></div></section></div>}
    {keyToRemove && <ConfirmDialog eyebrow="REMOTE ACCESS" title={`Remove “${keyToRemove.name}”?`} message={`This removes the selected public key from ${session.host}. Make sure another working authentication method is available before continuing.`} confirmLabel="Remove from host" danger busy={Boolean(installingKey)} onCancel={() => setKeyToRemove(null)} onConfirm={async () => { setInstallingKey(keyToRemove.privateKeyPath); setKeyMessage(`Removing ${keyToRemove.name}…`); try { await window.hedge.removePublicKey(liveConnectionId, keyToRemove.privateKeyPath); setInstalledPublicKeys(current => current.filter(value => value !== keyToRemove.publicKey)); setKeyMessage(`${keyToRemove.name} was removed from ${session.host}.`); setKeyToRemove(null); } catch (error) { setKeyMessage(`Could not remove ${keyToRemove.name}: ${error instanceof Error ? error.message : String(error)}`); } finally { setInstallingKey(''); } }} />}
    {authFailed && <div className="overlay"><form className="dialog auth-retry" onSubmit={retryAuthentication}><div className="host-key-icon auth-icon">!</div><small>AUTHENTICATION REJECTED</small><h2>Try your credentials again</h2><p>The host is reachable, but it rejected the supplied {session.authMethod === 'password' ? 'password' : 'key passphrase'}.</p><label>{session.authMethod === 'password' ? 'Password' : 'Private key passphrase'}<input autoFocus type="password" value={retrySecret} onChange={event => setRetrySecret(event.target.value)} placeholder="Enter a different credential" /></label>{session.credentialSetId && <p className="hint">This is a one-time override. The saved credential set will not be changed.</p>}<div className="actions"><button type="button" className="secondary" onClick={onClose}>Close tab</button><button className="primary" type="submit">Retry connection</button></div></form></div>}
    {hostPrompt && <div className="overlay"><section className={`dialog host-key-dialog ${hostPrompt.changed ? 'host-key-changed' : ''}`}><div className="host-key-icon">{hostPrompt.changed ? '!' : '✓'}</div><small>{hostPrompt.changed ? 'HOST IDENTITY CHANGED' : 'NEW SSH HOST'}</small><h2>{hostPrompt.changed ? 'Do not continue until verified' : 'Trust this host?'}</h2><p>{hostPrompt.changed ? 'The saved key does not match the key presented by this device. This may be a legitimate replacement—or a security risk.' : 'HedgeCon has not connected to this host before. Verify the fingerprint with a trusted source.'}</p><div className="fingerprint"><span>{hostPrompt.host}</span><code>SHA-256&nbsp; {hostPrompt.fingerprint}</code></div><div className="actions"><button className="secondary" onClick={() => answerHostKey(false)}>Cancel connection</button><button className={hostPrompt.changed ? 'danger-button' : 'primary'} onClick={() => answerHostKey(true)}>{hostPrompt.changed ? 'Trust new key' : 'Trust and connect'}</button></div></section></div>}
  </section>;
}
