import { FormEvent, useEffect, useRef, useState } from 'react';
import RFB from '@novnc/novnc';
import type { Session } from './types';

export default function VncView({ tabId, session, onClose }: { tabId: string; session: Session; onClose: () => void }) {
  const root = useRef<HTMLElement>(null); const screen = useRef<HTMLDivElement>(null); const [password, setPassword] = useState(''); const [savedPassword, setSavedPassword] = useState<string | null>(null); const [connectPassword, setConnectPassword] = useState<string | null>(null); const [status, setStatus] = useState(session.remoteCredentialSetId ? 'Loading saved credentials…' : 'Enter the VNC password to connect.'); const [error, setError] = useState('');
  useEffect(() => { if (!session.remoteCredentialSetId) { setSavedPassword(null); return; } let active = true; void window.hedge.getRemoteCredential(session.remoteCredentialSetId).then(credential => { if (!active) return; setSavedPassword(credential.password); setStatus('Saved credentials ready.'); }).catch(reason => { if (!active) return; setError(reason instanceof Error ? reason.message : String(reason)); setStatus('Could not load saved credentials.'); }); return () => { active = false; }; }, [session.remoteCredentialSetId]);
  useEffect(() => { if (connectPassword === null || !screen.current || !session.vncPort) return; let viewer: RFB | null = null; let cancelled = false; setStatus('Connecting…'); setError('');
    void window.hedge.createVncBridge(tabId, session.host, session.vncPort).then(({ url }) => { if (cancelled || !screen.current) return; viewer = new RFB(screen.current, url, { credentials: { password: connectPassword } }); viewer.scaleViewport = true; viewer.resizeSession = true; viewer.clipViewport = false; viewer.focusOnClick = true; viewer.addEventListener('connect', () => setStatus('Connected')); viewer.addEventListener('disconnect', event => { const clean = (event as CustomEvent<{ clean: boolean }>).detail?.clean; setStatus('Disconnected'); if (!clean) setError('The VNC connection ended unexpectedly. Check the address, password, and server settings.'); }); viewer.addEventListener('credentialsrequired', () => viewer?.sendCredentials({ password: connectPassword })); viewer.addEventListener('securityfailure', event => setError((event as CustomEvent<{ reason?: string }>).detail?.reason || 'The VNC server rejected the connection.')); }).catch(reason => setError(reason instanceof Error ? reason.message : String(reason)));
    return () => { cancelled = true; try { viewer?.disconnect(); } catch { /* Already disconnected. */ } window.hedge.destroyVncBridge(tabId); };
  }, [tabId, session.host, session.vncPort, connectPassword]);
  const connect = (event: FormEvent) => { event.preventDefault(); try { const settings = JSON.parse(localStorage.getItem('hedgecon-ui-settings') || '{}'); if (settings.remoteDesktopFullscreen && root.current && !document.fullscreenElement) void root.current.requestFullscreen().catch(() => undefined); } catch { /* Use windowed mode when settings are unavailable. */ } setConnectPassword(savedPassword ?? password); setPassword(''); };
  return <section ref={root} className="vnc-view"><header><div><strong>{session.name}</strong><small>VNC · {session.host}:{session.vncPort}</small></div><span>{status}</span><button onClick={onClose} title="Close VNC tab">×</button></header>{connectPassword === null ? <form className="vnc-login" onSubmit={connect}><div className="host-key-icon">◉</div><h2>Connect with VNC</h2><p>{session.remoteCredentialSetId ? 'Use the locally saved credential set for this connection.' : 'The password is used for this connection only and is never saved.'}</p>{!session.remoteCredentialSetId && <label>VNC password<input autoFocus type="password" value={password} onChange={event => setPassword(event.target.value)} /></label>}<button className="primary" disabled={Boolean(session.remoteCredentialSetId) && savedPassword === null}>Connect</button></form> : <><div ref={screen} className="vnc-screen" tabIndex={0} />{error && <div className="browser-error"><strong>VNC connection failed</strong><span>{error}</span><button className="secondary" onClick={() => setConnectPassword(null)}>Try again</button></div>}</>}</section>;
}
